### PR TITLE
cache Mustache::Context#mustache_in_stack

### PR DESCRIPTION
**Pull request by KillaPL**
require 'benchmark/ips'
    require 'mustache'

    template = """
    {{#products}}
      <div class='product_brick'>
        <div class='container'>
          <div class='element'>
            
          </div>
          <div class='element description'>
            <a href={{url}} class='product_name block bold'>
              {{external_index}}
            </a>
            Fire protection devices protect lives and material assets, thus, international, European and domestic standards and requirements have been formulated for them.
          </div>
        </div>
      </div>
    {{/products}}
    """

    data_10 = {
      products: []
    }

    10.times do
      data_10[:products] << {
        :external_index=>"ZSP135-DR-2A-1",
        :url=>"/products/7",
        :image=>"products/ZSP135-DR-2A-1 f.jpg"
      }
    end

    data_100 = {
      products: []
    }

    100.times do
      data_100[:products] << {
        :external_index=>"ZSP135-DR-2A-1",
        :url=>"/products/7",
        :image=>"products/ZSP135-DR-2A-1 f.jpg"
      }
    end

    data_1000 = {
      products: []
    }

    1000.times do
      data_1000[:products] << {
        :external_index=>"ZSP135-DR-2A-1",
        :url=>"/products/7",
        :image=>"products/ZSP135-DR-2A-1 f.jpg"
      }
    end

    Benchmark.ips do |x|
      x.report("render list of 10") do |times|
        Mustache.render(template, data_10)
      end

      x.report("render list of 100") do |times|
        Mustache.render(template, data_100)
      end

      x.report("render list of 1000") do |times|
        Mustache.render(template, data_1000)
      end
    end

    BEFORE
    Calculating -------------------------------------
       render list of 10   136.000  i/100ms
      render list of 100    58.000  i/100ms
     render list of 1000     8.000  i/100ms
    -------------------------------------------------
       render list of 10    192.406k (± 9.1%) i/s -    924.256k
      render list of 100     34.649k (±12.2%) i/s -    167.214k
     render list of 1000    714.832  (± 9.2%) i/s -      3.536k

    AFTER
    Calculating -------------------------------------
       render list of 10   138.000  i/100ms
      render list of 100    61.000  i/100ms
     render list of 1000     9.000  i/100ms
    -------------------------------------------------
       render list of 10    196.999k (± 9.5%) i/s -    946.404k
      render list of 100     38.943k (±10.7%) i/s -    188.978k
     render list of 1000    872.221  (± 8.8%) i/s -      4.320k

Providing an performance improvement from 2.4% for list with 10 elements, 13% for list with to 22% for list with 1000 elements. The data comes from application I work on and the bencharked code happens on my main page, so I care about performance for this. While I probably won't render 1000 objects, I certainly expect to render around 100.

I would also like to look into other things that allow me to improve this easily.

### CODE REVIEW

**Comment by locks** [comment]
Thanks for the PR :)
Could you create a `benchmarks` folder and put yours in there? I think we should start tracking it somehow.

**Comment by KillaPL** [comment]
With pleasure. I will do that tomorrow, I'm already a little tired. Will simplified benchmark presented above be good enough?

**Comment by locks** [comment]
Yes it will. You can just copy-paste it, thanks.

**Comment by KillaPL** [comment]
@locks Added a benchmark.

**Pull request merged**
