### PR TITLE
Add CONTRIBUTING.

### LINKED ISSUE #166: Add a CONTRIBUTING.md
Include instructions for updating the manpages, at the very least :)

### PR DESCRIPTION
**Pull request by bobthecow**
Fixes #166

### CODE REVIEW

**Comment by locks** [comment]
I thought I had merged this. Could you rebase please?

**Comment by bobthecow** [comment]
It doesn't need to rebase, it's just one file :)

**Comment by locks** [comment]
Oops, nevermind :P

**Comment by bobthecow** [comment]
Thank you :)

**Pull request merged**
